### ISSUE TITLE
Using python to create a DOCKER CONFIGURATION!!!!!

### ISSUE THREAD

**Issue by isiktantanis** [BarisUlas/CQL_Wrapper#1]
This a great antipattern and cassandra image with docker-compose must be used with Dockerfile and docker-compose.yaml instead!

Docker compose configuration: https://docs.docker.com/compose/gettingstarted/
Cassandra docker image: https://hub.docker.com/_/cassandra

**Comment by BarisUlas** [comment]
Hello Işıktan,

Thank you for your feedback. While I do realize this is an antipattern in terms of development lifecycle, it's important to note that Docker Compose is not an essential component of this project. The use of Docker Compose, Dockerfile, and docker-compose.yaml is suggested for better manageability and ease of deployment, but it's not mandatory.

The provided Docker Compose configuration is merely a recommendation for users who prefer a standardized and streamlined approach to deploying the Cassandra image in a containerized environment. Users who may have different preferences or existing infrastructure may choose to deploy the Cassandra image using alternative methods.

Feel free to reach out if you have any further questions or concerns.

Best regards.

**Comment by isiktantanis** [comment]
L + Ratio.
